version: 2

models:
  - name: stg_customers
    description: "Staging table for customers."
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: email_address
        tests:
          - not_null

  - name: stg_branches
    description: "Staging table for branches."
    columns:
      - name: branch_id
        tests:
          - unique
          - not_null
