name: 'fufu_dbt'
version: '1.0'
config-version: 2

profile: 'snowflake'

# Define your models paths
model-paths: ["models"]
seed-paths: ["data"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

# Configure database, schema, and target environment
vars:
  raw_database: RAW
  raw_schema: PUBLIC

on-run-end:
  - "GRANT SELECT ON ALL TABLES IN RAW.PUBLIC TO USER joseph;"

seeds:
  raw:
    branches:
      +schema: "PUBLIC"
    customers:
      +schema: "PUBLIC"
    inventory:
      +schema: "PUBLIC"
    menu_items:
      +schema: "PUBLIC"
    order_items:
      +schema: "PUBLIC"
    orders:
      +schema: "PUBLIC"
    payment_methods:
      +schema: "PUBLIC"
