snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: allyayc-mda43570
      user: SAMNJOROGE
      password: Sn-38241394
      role: ACCOUNTADMIN
      database: RAW
      warehouse: FUFU_REPUBLIC
      schema: PUBLIC
      threads: 4
      client_session_keep_alive: False
  
