snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <account-name>
      user: <user-name>
      password: <password>
      role: <role>
      database: RAW
      warehouse: FUFU_REPUBLIC
      schema: PUBLIC
      threads: 4
      client_session_keep_alive: False
  
